export default {
  SUBSCRIBE_REQUEST: '@meetup/SUBSCRIBE_REQUEST',
  CANCEL_SUBSCRIPTION_REQUEST: '@meetup/CANCEL_SUBSCRIPTION_REQUEST',
  SUBSCRIBE_SUCCESS: '@meetup/SUBSCRIBE_SUCCESS',
  SUBSCRIBE_FAILURE: '@meetup/SUBSCRIBE_FAILURE',
  CANCEL_SUBSCRIPTION_SUCCESS: '@meetup/CANCEL_SUBSCRIPTION_SUCCESS',
  CANCEL_SUBSCRIPTION_FAILURE: '@meetup/CANCEL_SUBSCRIPTION_FAILURE',
};
